export const FETCH_PEOPLES_LIST = "FETCH_PEOPLES_LIST";
export const FETCH_PLANETS_LIST = "FETCH_PLANETS_LIST";
export const FETCH_STARSHIPS_LIST = "FETCH_STARSHIPS_LIST";

export const FETCH_PEOPLE_DETAIL = "FETCH_PEOPLE_DETAIL";
export const FETCH_PLANET_DETAIL = "FETCH_PLANET_DETAIL";
export const FETCH_STARSHIP_DETAIL = "FETCH_STARSHIP_DETAIL";

export const SHOW_LOADER = "SHOW_LOADER";
export const FETCH_ERROR = "SHOW_ERROR";

export const SEARCH_TERM = "SEARCH_TERM";
export const FETCH_SEARCH_ITEMS = "FETCH_SEARCH_ITEMS";

export const TOGGLE_MENU = "TOGGLE_MENU";
